### ISSUE TITLE
Voice Command Notes Sample - doesn't work

### ISSUE THREAD

**Issue by nicksav** [googlesamples/glass-enterprise-samples#25]
We are not able to make a Notes sample to work. 
The app runs fine, and mic is working and when adding notes with tap - we can record and get text.
But commands dont work. The mic on the bottom left corner showing that there is focus happening, just the app does not fo anything.

We tried:
Add Note
Add
Next

Please advice.

Thanks
Nick

**Comment by nicksav** [comment]
I think we got it. The recognition part is really poor. (especially with non native English speakers). Also we found a bug, when saying 'Next' -> it is actually for some reason making 'Next Next'.

**Comment by jbolinger** [comment]
Hi @nicksav, glad you got it working but sorry to hear about the other troubles. You should be able to use most Android libraries on Glass including that one or the underlying Google Cloud Speech API. The online speech services do have a lot more functionality than what we can currently bring on device.

I'll close this since you got it working, but feel free to open new issues if there's anything more we can do to help.
